# Generated by Django 3.1.3 on 2020-11-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(help_text='Imagem do produto', upload_to='static/images/'),
        ),
    ]
